name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2
    
    - name: Start services
      run: docker-compose up -d
    
    - name: Wait for services to be ready
      run: sleep 10
    
    - name: Run integration tests
      run: docker-compose exec -T backend npm run test:integration
    
    - name: Stop services
      run: docker-compose down