name: PR Docker Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install GitHub CLI
        run: |
          wget -q https://github.com/cli/cli/releases/download/v2.45.0/gh_2.45.0_linux_amd64.deb
          sudo dpkg -i gh_2.45.0_linux_amd64.deb

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Debug - List existing packages
        run: |
          echo "Listing existing packages..."
          gh api /user/packages | jq .

      - name: Extract metadata for Backend
        id: meta-backend
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}-backend
          tags: |
            type=raw,value=pr-${{ github.event.pull_request.number }}
            type=raw,value=sha-${{ github.sha }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          provenance: false
          sbom: false

      - name: Debug - Verify Backend package
        run: |
          echo "Verifying backend package..."
          gh api /user/packages | jq .

      - name: Extract metadata for Frontend
        id: meta-frontend
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}-frontend
          tags: |
            type=raw,value=pr-${{ github.event.pull_request.number }}
            type=raw,value=sha-${{ github.sha }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          provenance: false
          sbom: false

      - name: Debug - Verify Frontend package
        run: |
          echo "Verifying frontend package..."
          gh api /user/packages | jq .
